################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2018-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

property:
  gpu-id: 0
  net-scale-factor: 0.0039215697906911373
  infer-dims: 3;544;960
  onnx-file: ../models/peoplenet/resnet34_peoplenet_int8.onnx
  int8-calib-file: ../models/peoplenet/resnet34_peoplenet_int8.txt
  labelfile-path: ../models/peoplenet/labels.txt
  model-engine-file: ../models/peoplenet/resnet34_peoplenet_int8.onnx_b1_gpu0_int8.engine
  batch-size: 1
  process-mode: 1
  model-color-format: 0
  # 0: FP32, 1: INT8, 2: FP16 mode
  network-mode: 0
  num-detected-classes: 3
  interval: 0
  gie-unique-id: 1
  output-blob-names: output_bbox/BiasAdd:0;output_cov/Sigmoid:0
  cluster-mode: 3
  # We are interested only in the person class. Filter out bag and face classes.
  filter-out-class-ids: 1;2 # Filter out bag and face class.

# Use the config params below for NMS clustering mode
class-attrs-all:
  topk: 20
  nms-iou-threshold: 0.5
  pre-cluster-threshold: 0.3
  minBoxes: 3
  dbscan-min-score: 1.3
  eps: 0.15
  detected-min-w: 20
  detected-min-h: 20
  threshold: 0.7

# [property]
# ## model-specific params like paths to model, engine, label files, etc. are to be added by users

# gpu-id=0
# net-scale-factor=0.0039215697906911373
# input-dims=3;544;960;0
# uff-input-blob-name=input_1
# process-mode=1
# model-color-format=0
# ## 0=FP32, 1=INT8, 2=FP16 mode
# network-mode=1
# num-detected-classes=3
# interval=0
# gie-unique-id=1
# output-blob-names=output_cov/Sigmoid;output_bbox/BiasAdd
# ## 1=DBSCAN, 2=NMS, 3= DBSCAN+NMS Hybrid, 4 = None(No clustering)
# cluster-mode=3
# maintain-aspect-ratio=1

# [class-attrs-all]
# pre-cluster-threshold=0.3
# nms-iou-threshold=0.5
# minBoxes=3
# dbscan-min-score=1.3
# eps=0.15
# detected-min-w=20
# detected-min-h=20
