################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2022-2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

source:
  # location: ../../../../samples/streams/sample_720p.h264
  # location: /work/retail_cropped.264
  # location: /work/data/trimmed.h264
  location: ../deepstream-retail-analytics/files/0001_compressed.h264
  # location: rtsp://

streammux:
  batch-size: 1
  batched-push-timeout: 40000
  width: 1920
  height: 1080


# tracker:
#   tracker-width: 640
#   tracker-height: 384
#   gpu-id: 0
#   ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
#   # ll-config-file required to set different tracker types
#   # ll-config-file=../../../../samples/configs/deepstream-app/config_tracker_IOU.yml
#   # ll-config-file: ../../../../samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml
#   ll-config-file: ../../../../samples/configs/deepstream-app/config_tracker_NvDCF_accuracy.yml
#   # ll-config-file=../../../../samples/configs/deepstream-app/config_tracker_DeepSORT.yml
#   enable-batch-process: 1

msgconv:
  msg2p-lib: ../nvmsgconv/libnvds_msgconv.so
  #msg2p-lib: /opt/nvidia/deepstream/deepstream/lib/libnvds_msgconv.so
  payload-type: 0
  msg2p-newapi: 0
  frame-interval: 30

msgbroker:
  proto-lib: /opt/nvidia/deepstream/deepstream/lib/libnvds_kafka_proto.so
  conn-str: localhost;9092
  topic: detections
  sync: 0

sink:
  sync: 1

filesink:
  location: /opt/nvidia/deepstream/deepstream-6.1/sources/apps/sample_apps/deepstream-retail-analytics/retail_output.mp4
  sync: 0
